In [ ]:
a#1
class Customer:
  def __init__(self,name):
    self.name=name
  def greet(self,n1=None):
    self.name1=n1
    if n1==None:
      print("Hello!")
    else:
      print(f"Hello {self.name1}!")
  def purchase(self,*args):
    print(f"{self.name}, you purchased {len(args)} item(s):")
    for i in args:
      print(i)
customer_1 = Customer("Sam")
customer_1.greet()
customer_1.purchase("chips", "chocolate", "orange juice")
print("-----------------------------")
customer_2 = Customer("David")
customer_2.greet("David")
customer_2.purchase("orange juice")

Hello!
Sam, you purchased 3 item(s):
chips
chocolate
orange juice
-----------------------------
Hello David!
David, you purchased 1 item(s):
orange juice

In [ ]:
#2
class Panda:
  def __init__(self,name,gender,age):
    self.name=name
    self.gender=gender
    self.age=age

  def sleep(self,*multi):
    if len(multi)==1:
      if multi[0]>=3 and multi[0]<=5:
        var= f"{self.name} sleeps {multi[0]} hours daily and should have Mixed Veggies"
      elif multi[0]>=6 and multi[0]<=8:
        var=f"{self.name} sleeps {multi[0]} hours daily and should have Eggplant and Tofu"
      elif multi[0]>=9 and multi[0]<=11:
        var=f"{self.name} sleeps {multi[0]} hours daily and should have Broccoli Chicken"
    else:
      var=f"{self.name} duration is unknown thus should have only  bamboo leaves"
    return var


panda1 = Panda("Kunfu","Male", 5)
panda2=Panda("Pan Pan","Female",3)
panda3=Panda("Ming Ming","Female",8)

print("{} is a {} Panda Bear who is {} years old".format(panda1.name,panda1.gender,panda1.age))

print("{} is a {} Panda Bear who is {} years old".format(panda2.name,panda2.gender,panda2.age))

print("{} is a {} Panda Bear who is {} years old".format(panda3.name,panda3.gender,panda3.age))
print("===========================")
print(panda2.sleep(10))
print(panda1.sleep(4))
print(panda3.sleep())

Kunfu is a Male Panda Bear who is 5 years old
Pan Pan is a Female Panda Bear who is 3 years old
Ming Ming is a Female Panda Bear who is 8 years old
===========================
Pan Pan sleeps 10 hours daily and should have Broccoli Chicken
Kunfu sleeps 4 hours daily and should have Mixed Veggies
Ming Ming duration is unknown thus should have only  bamboo leaves

In [ ]:
#3
class Cat:
  def __init__(self,name="White",work="sitting"):
    self.name=name
    self.work=work
  def printCat(self):
    print(self.name,"cat is",self.work)
  def changeColor(self,color):
    self.name=color
    self.work="sitting"
    print(self.name,"cat is",self.work)
    self.work="jumping"
c1 = Cat()
c2 = Cat("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()

White cat is sitting
Black cat is sitting
Brown cat is jumping
Red cat is purring
Blue cat is sitting
Purple cat is sitting
Blue cat is jumping
Purple cat is jumping

In [ ]:
#4
class Student:
  def __init__(self,name=None):
    self.name1=name
  def quizcalc(self,*args):
    count=3
    sum=0
    for i in args:
      sum+=i
    self.var=sum/count
  def printdetail(self):
    if self.name1==None:
      print("Hello default student")
    else:
      print(f"Hello {self.name1}")
    print(f"Your average quiz score is {self.var}")
s1 = Student()
s1.quizcalc(10)
print('--------------------------------')
s1.printdetail()
s2 = Student('Harry')
s2.quizcalc(10,8)
print('--------------------------------')
s2.printdetail()
s3 = Student('Hermione')
s3.quizcalc(10,9,10)
print('--------------------------------')
s3.printdetail()

--------------------------------
Hello default student
Your average quiz score is 3.3333333333333335
--------------------------------
Hello Harry
Your average quiz score is 6.0
--------------------------------
Hello Hermione
Your average quiz score is 9.666666666666666

In [ ]:
#5
class Student:
  def __init__(self,*args):
    self.args=args
    if len(args)<=2:
      self.var=f"Name: {args[0]}\nID: {args[1]}\nDepartment: CSE"
    else:
      self.var=f"Name: {args[0]}\nID: {args[1]}\nDepartment: {args[2]}"
  def dailyEffort(self,hour):
    self.var2=f"Daily Effort: {hour} hour(s)"
    if hour<=2:
      self.var3=f"Suggetion: Should give more effort!"
    elif hour <= 4:
      self.var3=f"Suggestion: Keep up the good work!"
    else:
      self.var3=f"Suggestion: Excellent! Now motivate others."
  def printDetails(self):
    print(self.var)
    print(self.var2)
    print(self.var3)
harry = Student('Harry Potter', 123)
harry.dailyEffort(3)
harry.printDetails()	
print('========================')
john = Student("John Wick", 456, "BBA")
john.dailyEffort(2)
john.printDetails()
print('========================')
naruto = Student("Naruto Uzumaki", 777, "Ninja")
naruto.dailyEffort(6)
naruto.printDetails()

Name: Harry Potter
ID: 123
Department: CSE
Daily Effort: 3 hour(s)
Suggestion: Keep up the good work!
========================
Name: John Wick
ID: 456
Department: BBA
Daily Effort: 2 hour(s)
Suggetion: Should give more effort!
========================
Name: Naruto Uzumaki
ID: 777
Department: Ninja
Daily Effort: 6 hour(s)
Suggestion: Excellent! Now motivate others.

In [ ]:
#6
class Patient:
  def __init__(self,name,age):
    self.name=name
    self.age=age
    self.var=f"Name: {self.name}\nAge: {self.age}"
  def add_Symptom(self,*multi):
    self.emp=""
    for i in multi:
      self.emp+=i+", "
    self.var2=self.emp[:-2]
  def printPatientDetail(self):
    print(self.var)
    print("Symptoms:",self.var2)

p1 = Patient("Thomas", 23)
p1.add_Symptom("Headache")
p2 = Patient("Carol", 20)
p2.add_Symptom("Vomiting", "Coughing")
p3 = Patient("Mike", 25)
p3.add_Symptom("Fever", "Headache", "Coughing")
print("=========================")
p1.printPatientDetail()
print("=========================")
p2.printPatientDetail()
print("=========================")
p3.printPatientDetail()

=========================
Name: Thomas
Age: 23
Symptoms: Headache
=========================
Name: Carol
Age: 20
Symptoms: Vomiting, Coughing
=========================
Name: Mike
Age: 25
Symptoms: Fever, Headache, Coughing

In [ ]:
#7
class Match:
  def __init__(self,team):
    self.team=team.split("-")
    print(f"5..4..3..2..1.. Play !!!")
    self.var=0
    self.var1=0
    self.var2=1
  def add_run(self,run):
    self.var+=run
  def add_wicket(self,wic):
    self.var1=wic
  def add_over(self,over):
    if over<=4:
      self.var2=over
    else:
      print(f"Warning! Cannot add {over} over/s (5 over match)")
  def print_scoreboard(self):
    return f"Batting Team: {self.team[0]}\nBowling Team: {self.team[1]}\nTotal runs: {self.var} Wickets: {self.var1} Over: {self.var2}"
     

match1 = Match("Rangpur Riders-Cumilla Victorians")
print("=========================")
match1.add_run(4)
match1.add_run(6)
match1.add_over(1)
print(match1.print_scoreboard())
print("=========================")
match1.add_over(5)
print("=========================")
match1.add_wicket(1)
print(match1.print_scoreboard())

5..4..3..2..1.. Play !!!
=========================
Batting Team: Rangpur Riders
Bowling Team: Cumilla Victorians
Total runs: 10 Wickets: 0 Over: 1
=========================
Warning! Cannot add 5 over/s (5 over match)
=========================
Batting Team: Rangpur Riders
Bowling Team: Cumilla Victorians
Total runs: 10 Wickets: 1 Over: 1

In [ ]:
#8
class ParcelKoro:
  def __init__(self,name=None,weight=0):
    self.name1=name
    self.product_weight=weight
    if self.name1==None:
      self.var1=f"Customer Name: No name set"
    else:
      self.var1=f"Customer Name: {self.name1}"
  def calculateFee(self,val=None):
    self.val1=val
    self.var2=f"Product Weight: {self.product_weight}"
    if self.product_weight==0:
      total_fee=0
    else:
      if self.val1==None:
        total_fee=(self.product_weight*20)+50
      else:
        total_fee=(self.product_weight*20)+100
    self.var3=f"Total Fee: {total_fee}"
  def printDetails(self):
    print(self.var1)
    print(self.var2)
    print(self.var3)
print("**********************")
p1 = ParcelKoro()
p1.calculateFee()
p1.printDetails()
print("**********************")
p2 = ParcelKoro('Bob The Builder')
p2.calculateFee()
p2.printDetails()
print("----------------------------")
p2.product_weight = 15
p2.calculateFee()
p2.printDetails()
print("**********************")
p3 = ParcelKoro('Dora The Explorer', 10)
p3.calculateFee('Dhanmondi')
p3.printDetails()

**********************
Customer Name: No name set
Product Weight: 0
Total Fee: 0
**********************
Customer Name: Bob The Builder
Product Weight: 0
Total Fee: 0
----------------------------
Customer Name: Bob The Builder
Product Weight: 15
Total Fee: 350
**********************
Customer Name: Dora The Explorer
Product Weight: 10
Total Fee: 300

In [ ]:
#9
class Batsman:
  def __init__(self, *args):
    if len(args) == 3:
      self.batsman_name= args[0]
      self.runs = args[1]
      self.balls = args[2]
    else:
      self.batsman_name = 'New Batsman'
      self.runs = args[0]
      self.balls = args[1]  
  def printCareerStatistics(self):
    print(f"Name: {self.batsman_name}\nRuns Scored: {self.runs} , Balls Faced: {self.balls}")
  def battingStrikeRate(self):
    return (self.runs/self.balls) * 100  
  def setName(self, name):
    self.batsman_name = name
b1 = Batsman(6101, 7380)
b1.printCareerStatistics()
print("============================")
b2 = Batsman("Liton Das", 678, 773)
b2.printCareerStatistics()
print("----------------------------")
print(b2.battingStrikeRate())
print("============================")
b1.setName("Shakib Al Hasan")
b1.printCareerStatistics()
print("----------------------------")
print(b1.battingStrikeRate())

Name: New Batsman
Runs Scored: 6101 , Balls Faced: 7380
============================
Name: Liton Das
Runs Scored: 678 , Balls Faced: 773
----------------------------
87.71021992238033
============================
Name: Shakib Al Hasan
Runs Scored: 6101 , Balls Faced: 7380
----------------------------
82.66937669376694

In [ ]:
#10
class EPL_Team:
  def __init__(self,name,song=None):
    self.name=name
    self.song1=song
    self.title=0
  def increaseTitle(self):
    self.title+=1
  def changeSong(self,new):
    self.song1=new
  def showClubInfo(self):
    if self.song1==None:
      self.var1=f"No Slogan"
    else:
      self.var1=f"Song: {self.song1}"
    return f"Name: {self.name}\n{self.var1}\nTotal no of title: {self.title}"
        
manu = EPL_Team('Manchester United', 'Glory Glory Man United')
chelsea = EPL_Team('Chelsea')
print('===================')
print(manu.showClubInfo())
print('##################')
manu.increaseTitle()
print(manu.showClubInfo())
print('===================')
print(chelsea.showClubInfo())
chelsea.changeSong('Keep the blue flag flying high')
print(chelsea.showClubInfo())

===================
Name: Manchester United
Song: Glory Glory Man United
Total no of title: 0
##################
Name: Manchester United
Song: Glory Glory Man United
Total no of title: 1
===================
Name: Chelsea
No Slogan
Total no of title: 0
Name: Chelsea
Song: Keep the blue flag flying high
Total no of title: 0

In [ ]:
#11
class Author:
  def __init__(self, name='Default', *books):
    self.name = name
    self.books = books
  def changeName(self, name):
    self.name = name  
  def addBooks(self, *books):
    self.books = books
  def printDetails(self):
    print(f'Author Name: {self.name}')  
    print('--------')  
    print('List of Books:') 
    for i in self.books:
      print(i)


auth1 = Author('Humayun Ahmed')
auth1.addBooks('Deyal', 'Megher Opor Bari')
auth1.printDetails()
print('===================')
auth2 = Author()
print(auth2.name)
auth2.changeName('Mario Puzo')
auth2.addBooks('The Godfather', 'Omerta', 'The Sicilian')
print('===================')
auth2.printDetails()
print('===================')
auth3 = Author('Paolo Coelho', 'The Alchemist', 'The Fifth Mountain')
auth3.printDetails()

Author Name: Humayun Ahmed
--------
List of Books:
Deyal
Megher Opor Bari
===================
Default
===================
Author Name: Mario Puzo
--------
List of Books:
The Godfather
Omerta
The Sicilian
===================
Author Name: Paolo Coelho
--------
List of Books:
The Alchemist
The Fifth Mountain

In [5]:
#12
class TaxiLagbe:
  def __init__(self, taxi_num, area):
    self.taxi_num = taxi_num
    self.area = area
    self.taka = 0
    self.pss_list = []

  def addPassenger(self, *passengers):

      if len(self.pss_list) >= 4:
        print('Taxi Full! No more passengers can be added.')

      else:
        for i in passengers:
          x,y = i.split('_')
          self.taka += int(y)
          self.pss_list.append(x)
          print(f'Dear {x}! Welcome to TaxiLagbe.')

  def printDetails(self):

      print(f'Trip info for Taxi number: {self.taxi_num}')
      print(f'This taxi can cover only {self.area} area.')
      print(f'Total passengers:{len(self.pss_list)}')
      print(f'Passenger lists:')
      for i in range(len(self.pss_list)):
        if i!=len(self.pss_list)-1:
          print(self.pss_list[i],end=",")
        else:
          print(self.pss_list[i],end="")
      print()
      print(f'Total collected fare: {self.taka} Taka')


taxi1 = TaxiLagbe('1010-01', 'Dhaka')
print('-------------------------------')
taxi1.addPassenger('Walker_100', 'Wood_200')
taxi1.addPassenger('Matt_100')
taxi1.addPassenger('Wilson_105')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi1.addPassenger('Karen_200')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi2 = TaxiLagbe('1010-02', 'Khulna')
taxi2.addPassenger('Ronald_115')
taxi2.addPassenger('Parker_215')
print('-------------------------------')
taxi2.printDetails()

-------------------------------
Dear Walker! Welcome to TaxiLagbe.
Dear Wood! Welcome to TaxiLagbe.
Dear Matt! Welcome to TaxiLagbe.
Dear Wilson! Welcome to TaxiLagbe.
-------------------------------
Trip info for Taxi number: 1010-01
This taxi can cover only Dhaka area.
Total passengers:4
Passenger lists:
Walker,Wood,Matt,Wilson
Total collected fare: 505 Taka
-------------------------------
Taxi Full! No more passengers can be added.
-------------------------------
Trip info for Taxi number: 1010-01
This taxi can cover only Dhaka area.
Total passengers:4
Passenger lists:
Walker,Wood,Matt,Wilson
Total collected fare: 505 Taka
-------------------------------
Dear Ronald! Welcome to TaxiLagbe.
Dear Parker! Welcome to TaxiLagbe.
-------------------------------
Trip info for Taxi number: 1010-02
This taxi can cover only Khulna area.
Total passengers:2
Passenger lists:
Ronald,Parker
Total collected fare: 330 Taka

In [ ]:
#13
class Account:
    def __init__(self, name=None, balance=None):
        self.name = name
        self.balance = balance

        if self.name == None:
            self.name = "Default Account"

        if self.balance == None:
            self.balance = 0.0

    def withdraw(self, amount):
        var = self.balance - amount
        if var <= 3070.0:
            print("Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.")
        else:
            print(f"Withdraw successful! New balance is: {var}")

    def details(self):
        return f"{self.name}\n{self.balance}"
a1 = Account()
print(a1.details())
print("------------------------")
a1.name = "Oliver"
a1.balance = 10000.0
print(a1.details())
print("------------------------")
a2 = Account("Liam")
print(a2.details())
print("------------------------")
a3 = Account("Noah",400)
print(a3.details())
print("------------------------")
a1.withdraw(6930)
print("------------------------")
a2.withdraw(600)
print("------------------------")
a1.withdraw(6929)

Default Account
0.0
------------------------
Oliver
10000.0
------------------------
Liam
0.0
------------------------
Noah
400
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Sorry, Withdraw unsuccessful! The account balance after deducting withdraw amount is equal to or less than minimum.
------------------------
Withdraw successful! New balance is: 3071.0

In [ ]:
#14
class StudentDatabase:
  def __init__(self, name, id):
    self.name = name
    self.id = id
    self.grades = {}
  def calculateGPA(self,l,sem):
    self.sem = sem
    dic = {}
    course = ""
    grade = 0
    for i in l:
      course += i[:6] +','
      grade += float(i[-3:])

    lis = course.split(',')
    final = tuple(lis[:-1])
    self.newcor = final
    
    self.gpa = round(grade/len(l), 2)
    dic[self.newcor] = self.gpa
    
    self.grades[self.sem] = dic

    return self.grades
  def printDetails(self):
    print(f"Name: {self.name} \nID: {self.id} \nCourses taken in {self.sem}:")
    for i in range(len(self.newcor)-1):
      print((self.newcor[i]),end=", ")
    print((self.newcor[i+1]))

    print("GPA:",self.gpa)



s1 = StudentDatabase('Pietro', '10101222')
s1.calculateGPA(['CSE230: 4.0', 'CSE220: 4.0', 'MAT110: 4.0'], 
'Summer2020')
s1.calculateGPA(['CSE250: 3.7', 'CSE330: 4.0'], 'Summer2021')
print(f'Grades for {s1.name}\n{s1.grades}')
print('------------------------------------------------------')
s1.printDetails()
s2 = StudentDatabase('Wanda', '10103332')
s2.calculateGPA(['CSE111: 3.7', 'CSE260: 3.7', 'ENG101: 4.0'], 
'Summer2022')
print('------------------------------------------------------')
print(f'Grades for {s2.name}\n{s2.grades}')
print('------------------------------------------------------')
s2.printDetails()

Grades for Pietro
{'Summer2020': {('CSE230', 'CSE220', 'MAT110'): 4.0}, 'Summer2021': {('CSE250', 'CSE330'): 3.85}}
------------------------------------------------------
Name: Pietro
ID: 10101222
Courses taken in Summer2021:
CSE250, CSE330
GPA: 3.85
------------------------------------------------------
Grades for Wanda
{'Summer2022': {('CSE111', 'CSE260', 'ENG101'): 3.8}}
------------------------------------------------------
Name: Wanda
ID: 10103332
Courses taken in Summer2022:
CSE111, CSE260, ENG101
GPA: 3.8

UNGRADED TASKS

In [ ]:
#20
class Student:
  def __init__(self,name=None,dept=None):
    self.name=name
    self.dept=dept
    self.en_lst=[]
    if name==None and dept==None:
      print("Student name and Department need to be set")
    elif dept==None:
      print(f"Department for {self.name} needs to be set")
    else:
      print(f"{self.name} is from {self.dept} Department")
  def update_name(self,new_name):
    self.name=new_name
  def update_department(self,new_dept):
    self.dept=new_dept
  def enroll(self,*en):
    for i in en:
      self.en_lst.append(i)
  def printDetail(self):
    print(f"Name: {self.name}\nDepartment: {self.dept}\n{self.name} enrolled {len(self.en_lst)} course(s):")
    for j in range(len(self.en_lst)-1):
      print(self.en_lst[j],end=", ")
    print((self.en_lst[j+1]))
     
s1 = Student()
print("=========================")
s2 = Student("Carol")
print("=========================")
s3 = Student("Jon", "EEE")
print("=========================")
s1.update_name("Bob")
s1.update_department("CSE")
s2.update_department("BBA")
s1.enroll("CSE110", "MAT110", "ENG091")
s2.enroll("BUS101")
s3.enroll("MAT110", "PHY111")
print("###########################")
s1.printDetail()
print("=========================")
s2.printDetail()
print("=========================")
s3.printDetail()

Student name and Department need to be set
=========================
Department for Carol needs to be set
=========================
Jon is from EEE Department
=========================
###########################
Name: Bob
Department: CSE
Bob enrolled 3 course(s):
CSE110, MAT110, ENG091
=========================
Name: Carol
Department: BBA
Carol enrolled 1 course(s):

UnboundLocalError: ignored

In [ ]:
#21
class Student:
  def __init__(self,*args):
    self.name=args[0]
    self.id=args[1]
    self.dept=args[2]
  def details(self):
    return f"Name: {self.name}\nID: {self.id}\nDepartment: {self.dept}"
  def advise(self,*var):
    creds=0.0
    list1=[]
    for i in var:
      creds+=3
      list1.append(i)
    print(f"{self.name}, you have taken {creds} credits")
    print("List of courses:")
    for i in range(len(var)-1):
     print(var[i],end=", ")
    print(var[i+1])
    if len(var)==3:
      print("Status: OK")
    elif len(var)==2:
      print("Status: You have to take at least 1 more course.")
    elif len(var)==1:
      print("Status: You have to take at least 2 more course.")
    elif len(var)>4:
      var1=len(var)-4
      print(f"Status: You have to drop at least {var1} course.")
s1 = Student("Alice","20103012","CSE")
s2 = Student("Bob", "18301254","EEE")
s3 = Student("Carol", "17101238","CSE")
print("##########################")
print(s1.details())
print("##########################")
print(s2.details())
print("##########################")
s1.advise("CSE110", "MAT110", "PHY111")
print("##########################")
s2.advise("BUS101", "MAT120")
print("##########################")
s3.advise("MAT110", "PHY111", "ENG102",
"CSE111", "CSE230")

##########################
Name: Alice
ID: 20103012
Department: CSE
##########################
Name: Bob
ID: 18301254
Department: EEE
##########################
Alice, you have taken 9.0 credits
List of courses:
CSE110, MAT110, PHY111
Status: OK
##########################
Bob, you have taken 6.0 credits
List of courses:
BUS101, MAT120
Status: You have to take at least 1 more course.
##########################
Carol, you have taken 15.0 credits
List of courses:
MAT110, PHY111, ENG102, CSE111, CSE230
Status: You have to drop at least 1 course.

In [ ]:
#22
class Hotel:
  def __init__(self,var3):
    self.var3=var3
    self.id=0
    self.gid=0
  def addStuff(self,name,age,num=None):
    self.id+=1
    if num==None:
      self.num="000"
    else:
      self.num=num
    self.name=name
    self.age=age
    print(f"Stuff with id {self.id} is added")
  def getStuffById(self,var):
    return f"Staff id: {var}\nName: {self.name}\nAge: {self.age}\nPhon No.: {self.num}"
  def addGuest(self,name1,age1,num1=None):
    self.gid+=1
    if num1==None:
      self.num1="000"
    else:
      self.num1=num1
    self.name1=name1
    self.age1=age1
    print(f"Guest with id {self.gid} is added")
  def getGuestById(self,var2):
    return f"Guest id: {var2}\nName: {self.name1}\nAge: {self.age1}\nPhon No.: {self.num1}"
  def allStaffs(self):
    print(f"All Staffs:\nNumber of Staff: {self.id}")
    print()
    for i in :
      print(f"Staff ID: {self.id} Name: {self.name} Age: {self.age} Phone no: {self.num}")
  def allGuest(self):
    print(f"All Guests:\nNumber of Guests: {self.gid}")
    print()
    for i in self.gid:
      print(f"Guest ID: {self.gid} Name: {self.name1} Age: {self.age1} Phone no: {self.num1}")

h = Hotel("Lakeshore")
h.addStuff( "Adam", 26)
print("=================================")
print(h.getStuffById(1))
print("=================================")
h.addGuest("Carol",35,"123")
print("=================================")
print(h.getGuestById(1))
print("=================================")
h.addGuest("Diana", 32, "431")
print("=================================")
print(h.getGuestById(2))
print("=================================")
h.allStaffs()
print("=================================")
h.allGuest()

Stuff with id 1 is added
=================================
Staff id: 1
Name: Adam
Age: 26
Phon No.: 000
=================================
Guest with id 1 is added
=================================
Guest id: 1
Name: Carol
Age: 35
Phon No.: 123
=================================
Guest with id 2 is added
=================================
Guest id: 2
Name: Diana
Age: 32
Phon No.: 431
=================================
All Staffs:
Number of Staff: 1

TypeError: ignored

In [ ]:
#23
class Author:
  def __init__(self,name=None):
    self.name=name
    self.book_count=0
    self.dict1={}
  def setName(self,new):
    self.name=new
  def addBook(self,*args):
    if self.name==None:
      print("A book cant be added without author name!")
    else:
      self.book_name=args[0]
      self.book_type=args[1]
      self.book_count+=1
  def printDetail(self):
    print(f"Number of Books: {self.book_count}\nAuthor name: {self.name}")
    print(f"{self.book_type} : {self.book_name}")
a1 = Author()
print("=================================")
a1.addBook("Ice","Science Fiction")
print("=================================")
a1.setName("Anna Kavan")
a1.addBook("Ice", "Science Fiction")
a1.printDetail()
print("=================================")
a2 = Author('Humayun Ahmed')
a2.addBook('Onnobhubon', 'Science Fiction')
a2.addBook('Megher Upor Bari', 'Horror')
print("=================================")
a2.printDetail()
a2.addBook('Ireena', 'Science Fiction')
print("=================================")
a2.printDetail()
print("=================================")

=================================
A book cant be added without author name!
=================================
Number of Books: 1
Author name: Anna Kavan
Science Fiction : Ice
=================================
=================================
Number of Books: 2
Author name: Humayun Ahmed
Horror : Megher Upor Bari
=================================
Number of Books: 3
Author name: Humayun Ahmed
Science Fiction : Ireena
=================================

In [ ]:
#23
class Author:
 def __init__(self,a=None):
    self.name=a
    self.allbooks={}
    self.booknumber=0
 def setName(self,a):
    self.name=a
 def addBook(self,*a):
    if self.name!=None:
      self.booknumber+=1
      self.booklist=[]
      self.booklist.append(a[0])
      #print(a[0])
      if a[1] not in self.allbooks.keys():
        self.allbooks[a[1]]=self.booklist
        # print(self.allbooks[a[1]]) 
      else:
        self.allbooks[a[1]]+=self.booklist
        #print(self.booklist)
    else:
      print('A book can not be added without author name')
 def printDetail(self):
    #self.booknumber=0
    #for i in self.allbooks.values():
      #print(i)
      #for j in i:
        #self.booknumber+=1
    print(f'Number of Book(s):{self.booknumber}')
    print(f'Author Name:{self.name}')
    for key,value in self.allbooks.items():
      #print(i,j)
      print(f'{key}:',end='')
      print((', ').join(value)) 
a1 = Author()
print("=================================")
a1.addBook("Ice","Science Fiction")
print("=================================")
a1.setName("Anna Kavan")
a1.addBook("Ice", "Science Fiction")
a1.printDetail()
print("=================================")
a2 = Author('Humayun Ahmed')
a2.addBook('Onnobhubon', 'Science Fiction')
a2.addBook('Megher Upor Bari', 'Horror')
print("=================================")
a2.printDetail()
a2.addBook('Ireena', 'Science Fiction')
print("=================================")
a2.printDetail()
print("=================================")

=================================
A book can not be added without author name
=================================
Number of Book(s):1
Author Name:Anna Kavan
Science Fiction:Ice
=================================
=================================
Number of Book(s):2
Author Name:Humayun Ahmed
Science Fiction:Onnobhubon
Horror:Megher Upor Bari
=================================
Number of Book(s):3
Author Name:Humayun Ahmed
Science Fiction:Onnobhubon, Ireena
Horror:Megher Upor Bari
=================================

In [ ]:
#24
class Vaccine:
  def __init__(self,name,md_in,intrvl):
    self.name=name
    self.md_in=md_in
    self.intrvl=intrvl
class Person:
  def __init__(self,pname,age,ptype="General Citizen"):
    self.pname=pname
    self.age=age
    self.ptype=ptype
    self.vac=""
    self.firstdose=False
    self.secdose=False
  def pushVaccine(self,vacN,dose="1st dose"):
    if dose=="1st dose":
      if self.age>=25 or self.ptype=="Student":
        self.vac=vacN
        self.firstdose=True
        print("1st dose done for",self.pname)
      else:
        print("Sorry",self.pname,"minimum age for taking vaccines is 25 years now")
    else:
      self.vac.name=

In [ ]:
#15
class FinalT6A:
    def __init__(self, x, p):
        self.temp, self.sum, self.y = 4, 0, 1
        self.temp += 1
        self.y = self.temp - p
        self.sum = self.temp + x
        print(x, self.y, self.sum)
    def methodA(self):
        x = 0
        y = 0
        y = y + self.y
        x = self.y + 2 + self.temp
        self.sum = x + y + self.methodB(self.temp, y)
        print(x, y, self.sum)
    def methodB(self, temp, n):
        x = 0
        temp += 1
        self.y = self.y + temp
        x = x + 3 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
        return self.sum

q1 = FinalT6A(2,1)
q1.methodA()
q1.methodA()

2 4 7
7 10 24
11 4 39
13 16 68
17 10 95

In [ ]:
#16
class Quiz3A:
    def __init__(self, k = None):
        self.temp, self.sum, self.y = 4, 0, 0
        if k != None:
            self.temp += 1
            self.temp = self.temp
            self.sum = self.temp + k
            self.y = self.sum - 1
        else:
            self.y = self.temp - 1
            self.sum = self.temp + 1
            self.temp += 2    
    def methodB(self, m, n):
        x = 0
        self.temp += 1
        self.y = self.y + m + (self.temp)
        x = x + 2 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
        return self.sum

a1 = Quiz3A()
a1.methodB(1,2)
a2 = Quiz3A(3)
a2.methodB(2,4)
a1.methodB(2,1)
a2.methodB(1,3)

4 11 20
6 15 29
3 21 44
5 23 57

57

In [ ]:
class Test5:
  def __init__(self):
      self.sum = 0
      self.y = 0
  def methodA(self):   
      x=y=k=0
      msg = [5]  
      while (k < 2):
          y += msg[0]     
          x = y + self.methodB(msg, k)
          self.sum = x + y + msg[0]
          print(x ," " , y, " " , self.sum)
          k+=1 
  def methodB(self, mg2, mg1):
        x = 0
        self.y += mg2[0]
        x = x + 3 + mg1
        self.sum += x + self.y
        mg2[0] = self.y + mg1
        mg1 += x + 2
        print(x , " " ,self.y, " " , self.sum)
        return mg1

t1 = Test5()
t1.methodA()
t1.methodA()
t1.methodA()

3   5   8
10   5   20
4   10   34
17   10   38
3   15   56
10   5   30
4   30   64
27   20   78
3   35   116
10   5   50
4   70   124
47   40   158

In [ ]:
#18
class Test4:
    def __init__(self):
        self.sum, self.y = 0, 0
    def methodA(self):
        x, y = 0, 0
        msg = [0]
        msg[0] = 5
        y = y + self.methodB(msg[0])
        x = y + self.methodB(msg, msg[0])
        self.sum = x + y + msg[0]
        print(x, y, self.sum)
    def methodB(self, *args):
        if len(args) == 1:
            mg1 = args[0]
            x, y = 0, 0
            y = y + mg1
            x = x + 33 + mg1
            self.sum = self.sum + x + y
            self.y = mg1 + x + 2
            print(x, y, self.sum)
            return y
        else:
            mg2, mg1 = args
            x = 0
            self.y = self.y + mg2[0]
            x = x + 33 + mg1
            self.sum = self.sum + x + self.y
            mg2[0] = self.y + mg1
            mg1 = mg1 + x + 2
            print(x, self.y, self.sum)
            return self.sum

t3 = Test4()
t3.methodA()
t3.methodA()
t3.methodA()
t3.methodA()

38 5 43
38 50 131
136 5 196
38 5 239
38 50 327
332 5 392
38 5 435
38 50 523
528 5 588
38 5 631
38 50 719
724 5 784